---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config-demo
  namespace: default
data:
  property.1: hello
  property.2: world
  property.file: |-
    property.1=value-1
    property.2=value-2
    property.3=value-3

---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-demo-configmap
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: hello
        image: busybox
        args:
        - "bin/sh"
        - "-c"
        - "for i in 9 8 7 6 5 4 3 2 1; do echo $WORDS; done"
        env:
          - name: WORDS
            valueFrom:
              configMapKeyRef:
                name: config-demo
                key: property.1
