---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
      - name: hello
        image: paperhs/k8s-demo:release-0.0.6
        ports:
        - containerPort: 1323
---

apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    name: hello
spec:
  selector:
    name: hello
  ports:
  - protocol: TCP
    port: 1323
    targetPort: 1323
